= Getting Started

== Server Requirements

* PHP >= 8.2
* MySQL >= 5.7 or MariaDB >= 10.3
* BCMath PHP Extension
* Ctype PHP Extension
* Filter PHP Extension
* Hash PHP Extension
* DOM PHP Extension
* Fileinfo PHP extension
* JSON PHP Extension
* Mbstring PHP Extension
* OpenSSL PHP Extension
* PCRE PHP Extension
* PDO PHP Extension
* Session PHP Extension
* Tokenizer PHP Extension
* XML PHP Extension
* Imagick PHP Extension
* GD PHP Extension


== Laramagz package directory

The `laramagz-v3.2.0.zip` package contains the following files and folders.

    📒 laramagz-v3.2.0
        📂 app
            📄 app-v3.2.0.zip
        📂 database 
            📄 dblaramagz-v3.2.0.sql
        📂 documentation
            📄 documentation.html
        📂 update-3.1.1-to-3.2.0
            📄 laramagz.zip
        📂 vendor
            📄 joedixon.zip
        📄 CHANGELOG.txt    
        

== Update Guide (from v3.1.1 to v3.2.0)

- Upload `laramagz.zip` contained in the `update-v3.1.1-to-3.2.0` folder.
- Extract `laramagz.zip`, copy and paste into the laramagz folder.

If you install laramagz via git clone, after the `composer install` command, extract the zip file `joedixon.zip`, copy the `joedixon` folder then paste it into `laramagz/vendor`

=== Clear cache

Manually delete all cache in the following folders (except .gitignore file if present):

1. `laramagz/storage/framework/views`.
2. `laramagz/storage/framework/cache/data`.
3. `laramagz/storage/framework/sessions`.
4. `laramagz/bootstrap/cache`.

Clearing cache with artisan command:

    php artisan optimize:clear
